### ISSUE TITLE
[FYEO] Security Clearance revokes multiple times

### ISSUE THREAD

**Issue by darkdiplomat** [darkdiplomat/GES-GameModes#3]
Should ignore a player that has already had their clearance revoked but doesn't

**Comment by Gato-The-One** [comment]
Hey Diplomat. Big fan of your work. I've just figured out where your ges master zip files are (Me being a complete github noob, and all). And installed those modes to my server (Gato's Gamestop). AUF works like a charm, as does pop a cap, warpmod and t.ball. Bypass is interesting in play, but still trying to get a grasp of gameplay. Launch code is friggin awesome! Cap em all is also awesome, but buggy. 

Gotta CAp Em All
1. Some ppl get the list of targets, and some don't.

2. When someone new joins:
- Sometimes That person doesn't get a target list
-A person that was already in that acquires all targets, doesn't get an additional name added, yet the round doesn't end.

3. After a round ends with a legitimate winner. An admin has to restart the mode, because upon the next round, the round abruptly ends after one kill with no winner. And it repeats that way until admin restarts it.

Eyes Only (Briefcase)
1. Case wielder kills, but no one is eliminated

Launch code
1. sometimes scientist hacker spawns without weapons. (In all honesty to this. Everyone that had played this mode on my server agree that the hacker of both teams should have no weapon because it pushes that team aspect to the limits. Excellent mode bro)

Also,
I have sent a friend request via steam just today. 
If you see a "Gato's in your shadow" request. Its me. Thanks again

**Comment by Gato-The-One** [comment]
CapEmAll Recap

Okay, here's the skinny.
Everyone gets the list now. *Awesome*
if a target leaves, and they are your last target, you cant finish the round.
If a player joins mid-round they are held in spectate mode, which is a good addition.
However, they are unable to join when the round restarts. Admin must restart the mode manually to include them.
Otherwise, the mode runs smoothly.
